return function(entity, x, y)
  entity:assemble(ECS.a.characters.character, 700, 700)
  entity:give("playerControlled")
  entity:give("speed", 30)
  entity:give("size", 20, 32)
  entity:give("sprite", 'characters.player3')
  entity:give("lightSource", 400, 1, 0.8, 0.8, 1.0)
  entity:give("cameraTarget")
  entity:give("mana", 100)
  entity:give("physicsBody", { width = 13, height = 13, centered = true, tags = { "player" } })
end
