return function(entity, x, y)
  entity:assemble(ECS.a.characters.character, 700, 700)
  entity:give("playerControlled")
  entity:give("speed", 30)
  entity:give("size", 20, 32)
  entity:give("sprite", 'characters.player3')
  entity:give("lightSource", 450, 1, 0.8, 0.8, 1.0)
  entity:give("cameraTarget")
  entity:give("mana", 100)
  entity:give("physicsBody", 13, 13, { "player" })
end
